/**
 * make_version.ts — Regenerates src/version.ts from deno.json.
 *
 * Called by `mise run build` and the CI/bump workflows.
 * The generated file is committed to the repository.
 */
const configRaw = await Deno.readTextFile("./deno.json");
const config = JSON.parse(configRaw);
const version: string = config.version ?? "v0.0.0";

const content =
  `// This file is auto-generated by \`mise run build\`. Do not edit manually.\nexport const generatedVersion = "${version}";\n`;

await Deno.writeTextFile("./src/version.ts", content);
console.log(`✓ version.ts generated: ${version}`);
