#!/usr/bin/env bash
#MISE description="Bootstrap transcrypt from repo secret or create new"
set -euo pipefail
if [ -f "./scripts/transcrypt_bootstrap.sh" ]; then
  source ./scripts/transcrypt_bootstrap.sh
  transcrypt_bootstrap
else
  echo "⚠ transcrypt_bootstrap.sh not found. Skipping secrets init."
fi
